/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as SevillaRouteImport } from "./routes/sevilla"
import { Route as SedesRouteImport } from "./routes/sedes"
import { Route as PatrocinioRouteImport } from "./routes/patrocinio"
import { Route as PaisesInvitadosRouteImport } from "./routes/paises-invitados"
import { Route as FestSevillaRouteImport } from "./routes/fest-sevilla"
import { Route as EventoRouteImport } from "./routes/evento"
import { Route as ContactoRouteImport } from "./routes/contacto"
import { Route as ConceptoRouteImport } from "./routes/concepto"
import { Route as IndexRouteImport } from "./routes/index"

const SevillaRoute = SevillaRouteImport.update({
  id: "/sevilla",
  path: "/sevilla",
  getParentRoute: () => rootRouteImport,
} as any)
const SedesRoute = SedesRouteImport.update({
  id: "/sedes",
  path: "/sedes",
  getParentRoute: () => rootRouteImport,
} as any)
const PatrocinioRoute = PatrocinioRouteImport.update({
  id: "/patrocinio",
  path: "/patrocinio",
  getParentRoute: () => rootRouteImport,
} as any)
const PaisesInvitadosRoute = PaisesInvitadosRouteImport.update({
  id: "/paises-invitados",
  path: "/paises-invitados",
  getParentRoute: () => rootRouteImport,
} as any)
const FestSevillaRoute = FestSevillaRouteImport.update({
  id: "/fest-sevilla",
  path: "/fest-sevilla",
  getParentRoute: () => rootRouteImport,
} as any)
const EventoRoute = EventoRouteImport.update({
  id: "/evento",
  path: "/evento",
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: "/contacto",
  path: "/contacto",
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptoRoute = ConceptoRouteImport.update({
  id: "/concepto",
  path: "/concepto",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/concepto": typeof ConceptoRoute
  "/contacto": typeof ContactoRoute
  "/evento": typeof EventoRoute
  "/fest-sevilla": typeof FestSevillaRoute
  "/paises-invitados": typeof PaisesInvitadosRoute
  "/patrocinio": typeof PatrocinioRoute
  "/sedes": typeof SedesRoute
  "/sevilla": typeof SevillaRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/concepto": typeof ConceptoRoute
  "/contacto": typeof ContactoRoute
  "/evento": typeof EventoRoute
  "/fest-sevilla": typeof FestSevillaRoute
  "/paises-invitados": typeof PaisesInvitadosRoute
  "/patrocinio": typeof PatrocinioRoute
  "/sedes": typeof SedesRoute
  "/sevilla": typeof SevillaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/concepto": typeof ConceptoRoute
  "/contacto": typeof ContactoRoute
  "/evento": typeof EventoRoute
  "/fest-sevilla": typeof FestSevillaRoute
  "/paises-invitados": typeof PaisesInvitadosRoute
  "/patrocinio": typeof PatrocinioRoute
  "/sedes": typeof SedesRoute
  "/sevilla": typeof SevillaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/concepto"
    | "/contacto"
    | "/evento"
    | "/fest-sevilla"
    | "/paises-invitados"
    | "/patrocinio"
    | "/sedes"
    | "/sevilla"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/concepto"
    | "/contacto"
    | "/evento"
    | "/fest-sevilla"
    | "/paises-invitados"
    | "/patrocinio"
    | "/sedes"
    | "/sevilla"
  id:
    | "__root__"
    | "/"
    | "/concepto"
    | "/contacto"
    | "/evento"
    | "/fest-sevilla"
    | "/paises-invitados"
    | "/patrocinio"
    | "/sedes"
    | "/sevilla"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConceptoRoute: typeof ConceptoRoute
  ContactoRoute: typeof ContactoRoute
  EventoRoute: typeof EventoRoute
  FestSevillaRoute: typeof FestSevillaRoute
  PaisesInvitadosRoute: typeof PaisesInvitadosRoute
  PatrocinioRoute: typeof PatrocinioRoute
  SedesRoute: typeof SedesRoute
  SevillaRoute: typeof SevillaRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/sevilla": {
      id: "/sevilla"
      path: "/sevilla"
      fullPath: "/sevilla"
      preLoaderRoute: typeof SevillaRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/sedes": {
      id: "/sedes"
      path: "/sedes"
      fullPath: "/sedes"
      preLoaderRoute: typeof SedesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/patrocinio": {
      id: "/patrocinio"
      path: "/patrocinio"
      fullPath: "/patrocinio"
      preLoaderRoute: typeof PatrocinioRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/paises-invitados": {
      id: "/paises-invitados"
      path: "/paises-invitados"
      fullPath: "/paises-invitados"
      preLoaderRoute: typeof PaisesInvitadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/fest-sevilla": {
      id: "/fest-sevilla"
      path: "/fest-sevilla"
      fullPath: "/fest-sevilla"
      preLoaderRoute: typeof FestSevillaRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/evento": {
      id: "/evento"
      path: "/evento"
      fullPath: "/evento"
      preLoaderRoute: typeof EventoRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/contacto": {
      id: "/contacto"
      path: "/contacto"
      fullPath: "/contacto"
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/concepto": {
      id: "/concepto"
      path: "/concepto"
      fullPath: "/concepto"
      preLoaderRoute: typeof ConceptoRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConceptoRoute: ConceptoRoute,
  ContactoRoute: ContactoRoute,
  EventoRoute: EventoRoute,
  FestSevillaRoute: FestSevillaRoute,
  PaisesInvitadosRoute: PaisesInvitadosRoute,
  PatrocinioRoute: PatrocinioRoute,
  SedesRoute: SedesRoute,
  SevillaRoute: SevillaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
